micronaut:
  application:
    name: ktBookstore
  datasources:
    default:
      url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: admin
      password: '12345'
      schema-generate: CREATE_DROP
      dialect: H2